
site_name: geogeek

theme:
  custom_dir: overrides #-- to override the copyright
  features:
    - content.action.edit
  icon:
    logo: material/console
    edit: material/pencil 
    view: material/eye
  name: material
  palette:
    primary: blue grey

repo_url: https://github.com/tudelft3d/geogeek

# nav:
  # - Home222: index.md


edit_uri: edit/main/docs/
repo_name: tudelft3d/geogeek


# plugins:
#   - search
#   - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
