
site_name: geogeeks

theme:
  custom_dir: overrides #-- to override the copyright
  features:
    - content.action.edit
    # Links content tabs. If user selects MacOS on one page, tabs on other pages will also be set MacOS
    - content.tabs.link 
    - navigation.tabs
    - navigation.top
    # Add copy button to code blocks
    - content.code.copy
    # Enable annotations inside code blocks
    - content.code.annotate
  icon:
    logo: material/console
    edit: material/pencil 
    view: material/eye
  name: material
  palette:
    primary: deep purple
    # primary: custom

repo_url: https://github.com/tudelft3d/geogeeks

# nav:
  # - Home222: index.md


edit_uri: edit/main/docs/
repo_name: tudelft3d/geogeeks

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/extra.js

plugins:
  - search
  - awesome-pages
#   - mkdocstrings

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true # Add permalink symbol to end of headers
  - def_list # Ordered and unordered lists
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  # Content tabs (buttons to show different text based on selected tab)
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # Keyboard keys shortcuts